   #ALL THE HANGMAN PICS

def pic(count):
    if count == 0:
        print("  ______________________")
        print("  |                              ")
        print("  |                              ")
        print("  |                              ")
        print("  |                              ")
        print("  |                              ")
        print("  |                              ")
        print("  |                              ")
        print("  |                              ")
        print(" / \                             ")
        print("/   \                            ")
    elif count == 1:
        print("  ______________________")
        print("  |                    |        ")
        print("  |                             ")
        print("  |                             ")
        print("  |                             ")
        print("  |                             ")
        print("  |                             ")
        print("  |                             ")
        print("  |                             ")
        print(" / \                            ")
        print("/   \                           ")
    elif count == 2:
        print("  ______________________")
        print("  |                    |         ")
        print("  |                  /^.^\       ")
        print("  |                  \___/       ")
        print("  |                              ")
        print("  |                              ")
        print("  |                              ")
        print("  |                              ")
        print("  |                              ")
        print(" / \                             ")
        print("/   \                            ")
    elif count == 3:
        print("  ______________________")
        print("  |                    |         ")
        print("  |                  /^.^\       ")
        print("  |                  \___/       ")
        print("  |                    |         ")
        print("  |                    |         ")
        print("  |                              ")
        print("  |                              ")
        print("  |                              ")
        print(" / \                             ")
        print("/   \                            ")
    elif count == 4:
        print("  ______________________")
        print("  |                    |         ")
        print("  |                  /^.^\       ")
        print("  |                  \___/       ")
        print("  |                    |         ")
        print("  |                    |         ")
        print("  |                    |         ")
        print("  |                    |         ")
        print("  |                              ")
        print(" / \                             ")
        print("/   \                            ")
    elif count == 5:
        print("  ______________________")
        print("  |                    |         ")
        print("  |                  /^.^\       ")
        print("  |                  \___/       ")
        print("  |                 \__|         ")
        print("  |                    |         ")
        print("  |                    |         ")
        print("  |                    |         ")
        print("  |                              ")
        print(" / \                             ")
        print("/   \                            ")
    elif count == 6:
        print("  ______________________")
        print("  |                    |         ")
        print("  |                  /^.^\       ")
        print("  |                  \___/       ")
        print("  |                 \__|__/      ")
        print("  |                    |         ")
        print("  |                    |         ")
        print("  |                    |         ")
        print("  |                              ")
        print(" / \                             ")
        print("/   \                            ")
    elif count == 7:
        print("  ______________________")
        print("  |                    |         ")
        print("  |                  /^.^\       ")
        print("  |                  \___/       ")
        print("  |                 \__|__/      ")
        print("  |                    |         ")
        print("  |                    |         ")
        print("  |                    |         ")
        print("  |                   /          ")
        print(" / \                 /           ")
        print("/   \                            ")
    elif count == 8:
        print("  ______________________")
        print("  |                    |         ")
        print("  |                  /^.^\       ")
        print("  |                  \___/       STEVE DIED")
        print("  |                 \__|__/       YOU LOSE")
        print("  |                    |         ")
        print("  |                    |         ")
        print("  |                    |         ")
        print("  |                   / \        ")
        print(" / \                 /   \       ")
        print("/   \                            ")
